export const ORDER_LIST_REQUEST='ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE='ORDER_LIST_FAILURE'

export const GET_ORDER_LIST_REQUEST='GET_ORDER_LIST_REQUEST'
export const GET_ORDER_LIST_SUCCESS='GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAILURE='GET_ORDER_LIST_FAILURE'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE='ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'
